import 'package:get/get.dart';
import 'package:medical_store_app/core/constant/images.dart';
import 'package:medical_store_app/src/features/shop_Screen/model/medicine_model.dart';

class MedicinelistController extends GetxController {
  var model = [
    MedicineModel(
      name: "Paracetamol",
      power: "500 mg",
      quantity: '10 Tablets',
      price: "৳ 7",
      discountedPrice: "৳ 7",
      img: AppImages.pracetamol1,
      id: 1,
    ),
    MedicineModel(
      name: "Paracetamol",
      power: "500 mg",
      quantity: '10 Tablets',
      price: "৳ 7",
      discountedPrice: "৳ 7",
      img: AppImages.pracetamol2,
      id: 2,
    ),
    MedicineModel(
      name: "Paracetamol",
      power: "500 mg",
      quantity: '10 Tablets',
      price: "৳ 7",
      discountedPrice: "৳ 7",
      img: AppImages.pracetamol3,
      id: 3,
    ),
    MedicineModel(
      name: "Paracetamol",
      power: "500 mg",
      quantity: '10 Tablets',
      price: "৳ 7",
      discountedPrice: "৳ 7",
      img: AppImages.pracetamol1,
      id: 4,
    ),
    MedicineModel(
      name: "Paracetamol",
      power: "500 mg",
      quantity: '10 Tablets',
      price: "৳ 7",
      discountedPrice: "৳ 7",
      img: AppImages.pracetamol1,
      id: 5,
    ),
    MedicineModel(
      name: "Paracetamol",
      power: "500 mg",
      quantity: '10 Tablets',
      price: "৳ 7",
      discountedPrice: "৳ 7",
      img: AppImages.pracetamol1,
      id: 6,
    ),
    MedicineModel(
      name: "Paracetamol",
      power: "500 mg",
      quantity: '10 Tablets',
      price: "৳ 7",
      discountedPrice: "৳ 7",
      img: AppImages.pracetamol1,
      id: 7,
    ),
    MedicineModel(
      name: "Paracetamol",
      power: "500 mg",
      quantity: '10 Tablets',
      price: "৳ 7",
      discountedPrice: "৳ 7",
      img: AppImages.pracetamol1,
      id: 8,
    ),
    MedicineModel(
      name: "Paracetamol",
      power: "500 mg",
      quantity: '10 Tablets',
      price: "৳ 7",
      discountedPrice: "৳ 7",
      img: AppImages.pracetamol1,
      id: 9,
    ),
    MedicineModel(
      name: "Paracetamol",
      power: "500 mg",
      quantity: '10 Tablets',
      price: "৳ 7",
      discountedPrice: "৳ 7",
      img: AppImages.pracetamol1,
      id: 10,
    ),
    MedicineModel(
      name: "Paracetamol",
      power: "500 mg",
      quantity: '10 Tablets',
      price: "৳ 7",
      discountedPrice: "৳ 7",
      img: AppImages.pracetamol1,
      id: 11,
    ),
  ].obs;
}
